Context: first try accessing a public method, then resort to a property
Reason to this is that property_exists ignores all accessibility. Before this change,
even if we had a public method with the same name, we would cause a fatal error trying
to access a private property. Now this will only happen if there's no public method.

> Fatal error: Uncaught Error: Cannot access private property

Fixes #38